In [2]:
import numpy as np

 list vs numpy time take

In [10]:
list = [1,2,3,4,5]

In [11]:
np_array = np.array([1,2,3,4,5])
type(np_array)

numpy.ndarray

In [12]:
np_array.shape

(5,)

In [16]:
b = np.array( [(1,2,3,4,5), (6,7,8,9,10)])
b.shape

(2, 5)

In [18]:
c = np.array( [(1,2,3,4,5), (6,7,8,9,10)], dtype=float)

initial placeholder  un np

In [19]:
x=np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
q = np.ones((5,4))
q

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
w= np.full((2,6), 8)
w

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

MATRIX

In [23]:
e= np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

RANDOM

In [25]:
r=np.random.random((3,4))
r

array([[0.91861861, 0.20934522, 0.26801826, 0.69604369],
       [0.94060899, 0.71052228, 0.6837447 , 0.81708983],
       [0.39151446, 0.74198225, 0.15033068, 0.86767992]])

RANDOM INTEGER

In [29]:
t= np.random.randint(1,80,(2,3))
t

array([[35, 35, 45],
       [19, 39, 26]])

In [31]:
u = np.linspace(10,18, 5)# 5 numros entre 10 y 18
u

array([10., 12., 14., 16., 18.])

In [33]:
o= np.arange(10,30,5)
o

array([10, 15, 20, 25])

convertir una lista a NUMPY

In [34]:
lista=[10,20,30,40,50]
npLista= np.asarray(lista)
npLista

array([10, 20, 30, 40, 50])

In [36]:
p= np.random.randint(10,50,(4,5))
p

array([[39, 22, 22, 33, 41],
       [30, 15, 31, 19, 14],
       [24, 12, 37, 41, 21],
       [17, 37, 45, 41, 44]])

In [37]:
p.shape

(4, 5)

In [38]:
p.ndim

2

In [39]:
p.size

20

In [40]:
p.dtype

dtype('int32')

OPERACIONES MATEMATICA


In [42]:
lista1=[1,2,3,4,5]
lista2=[6,7,8,9,10]
lista1+lista2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
a = np.random.randint(0,9,(3,3))
b= np.random.randint(10,19,(3,3))
print(a)
print(b)

[[8 4 6]
 [2 6 4]
 [3 4 8]]
[[11 18 14]
 [12 14 13]
 [10 16 13]]


In [46]:
a+b

array([[19, 22, 20],
       [14, 20, 17],
       [13, 20, 21]])

In [47]:
a-b

array([[ -3, -14,  -8],
       [-10,  -8,  -9],
       [ -7, -12,  -5]])

In [48]:
a*b

array([[ 88,  72,  84],
       [ 24,  84,  52],
       [ 30,  64, 104]])

In [49]:
b/a

array([[1.375     , 4.5       , 2.33333333],
       [6.        , 2.33333333, 3.25      ],
       [3.33333333, 4.        , 1.625     ]])

In [51]:
np.add(a,b)

array([[19, 22, 20],
       [14, 20, 17],
       [13, 20, 21]])

se puede hacer los mismo de arriba con 
substract, multiply, divide

In [52]:
a


array([[8, 4, 6],
       [2, 6, 4],
       [3, 4, 8]])

INVERTIR LAS TABLAS

In [53]:
a.T

array([[8, 2, 3],
       [4, 6, 4],
       [6, 4, 8]])

RESHAPE

In [55]:
d= a.reshape(9,1)
d

array([[8],
       [4],
       [6],
       [2],
       [6],
       [4],
       [3],
       [4],
       [8]])